= Git demonstration notes
Ed Himwich
Version 0.4 - June 06, 2020

:sectnums:
:experimental:

:toc:

<<<

== Preamble

Generally the O'Rielly font conventions are followed, except:

* `monospace` is used for file names, commands, code, and text to be typed by user

*IMPORTANT* admonitions  are used to emphasize critical points.

*NOTE* admonitions are used to provide additional information that may be
useful, but are not part of the main discussion.

NOTE: The output in some examples may differ in small ways on the
version of Git being used. These notes were prepared using version
_2.26.2_.

NOTE: Extra blank lines have be added between commands in the listings
to improve readability. Also the colorization of the Git output has
been lost.

== A simple project: Hello, world!

=== Initial files
....
$ pwd
/Users/whimwich/Git/hello

$ ls
Makefile	hello.c

$ cat hello.c
#include <stdio.h>
int main() {
   printf("Hello, World!\n");
   return 0;
}

$ cat Makefile 
hello: hello.o

$ make
cc    -c -o hello.o hello.c
cc   hello.o   -o hello

$ ./hello 
Hello, World!
....

=== Make it Git!

Use `git init` to start
....
$ git init
Initialized empty Git repository in /Users/whimwich/Git/hello/.git/
....

All the Git data is in  the `.git` sub-directory:

....
$ tree .git
.git
├── HEAD
├── config
├── description
├── hooks
│   ├── applypatch-msg.sample
│   ├── commit-msg.sample
│   ├── fsmonitor-watchman.sample
│   ├── post-update.sample
│   ├── pre-applypatch.sample
│   ├── pre-commit.sample
│   ├── pre-merge-commit.sample
│   ├── pre-push.sample
│   ├── pre-rebase.sample
│   ├── pre-receive.sample
│   ├── prepare-commit-msg.sample
│   └── update.sample
├── info
│   └── exclude
├── objects
│   ├── info
│   └── pack
└── refs
    ├── heads
    └── tags

8 directories, 16 files
....

NOTE: You can live a quite happy Git life and never delve into the
`.git` sub-directory.  You may need to use it for some advanced
operations. The most likely things to be useful are `config` and
`refs`. The main store of data is in the `objects` directory.

NOTE: If you delete the `.git` sub-directory, you have removed Git and
all the history from your project.

=== `git status` is the basic command to see where you are

....
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Makefile
	hello
	hello.c
	hello.o

nothing added to commit but untracked files present (use "git add" to track)
....

The presence of _untracked_ files is a problem because they represent
either content that you have not added to Git yet or files you don't
want keep track of. In the latter case, this usually includes binary
files. Typically, you don't want to see any untracked files.

=== Use `.gitignore` to ignore files, especially binary ones

Git works best with ASCII files. It can store binary files when
needed, but it is most useful, and efficient, for source files.  It is
usually better to ignore binary files.

....
$ cp /tmp/.gitignore .
$ cat .gitignore 
*.o
hello

$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore
	Makefile
	hello.c

nothing added to commit but untracked files present (use "git add" to track)
....

NOTE: The `.gitignore` file has a syntax to allow fine-grained control
of what is ignored. The basic syntax, as shown in the example above,
   is fairly simple.

//$ git log
//fatal: your current branch 'master' does not have any commits yet

=== Add files to index

Add the files that aren't ignored to the index. The use of `.` adds
 all files in the current directory and below.
 
....
$ git add .

$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .gitignore
	new file:   Makefile
	new file:   hello.c

....

Now the files are no longer untracked, but are staged to be committed.

NOTE: The `status` command gives hints about how to undo an action.
This is just one example of the many ways Git has to undo what has
already happened.

=== Commit changes that are in the index

....
$ git commit -m "Initial commit"
[master (root-commit) bdca79e] Initial commit
 3 files changed, 8 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 Makefile
 create mode 100644 hello.c
....

NOTE: If you leave out the `-m` and the commit message, Git will
schedule an editor (_vi_ by default) so you can compose a, possibly
multi-line,  message.  The comments in the message (lines starting
        with `#`) are only informational. If you close the file
without adding anything, Git will abort the commit. 

=== Check status

....
$ git status
On branch master
nothing to commit, working tree clean
....

All clean!

=== Use `git log` to see the history

The history comes out in reverse (mostly chronological) order. Of course that
doesn't matter when you only have one commit.

....
$ git log
commit bdca79e9499918240c27ff43c6598b26db6c0893 (HEAD -> master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit

....

NOTE: The `commit` line shows the SHA of the commit (see
<<Git tracks content>>
below) and that this is the `HEAD` commit and the tip of
`master`.

The log is automatically piped through _less_.

==== Some other forms of `git log`

===== `--stat` for statistics
....
$ git log --stat
commit bdca79e9499918240c27ff43c6598b26db6c0893 (HEAD -> master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit

 .gitignore | 2 ++
 Makefile   | 1 +
 hello.c    | 5 +++++
 3 files changed, 8 insertions(+)
....

===== `-p` for patch listing
....
$ git log -p
commit bdca79e9499918240c27ff43c6598b26db6c0893 (HEAD -> master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit

diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..59b32b2
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1,2 @@
+*.o
+hello
diff --git a/Makefile b/Makefile
new file mode 100644
index 0000000..da75d00
--- /dev/null
+++ b/Makefile
@@ -0,0 +1 @@
+hello: hello.o
diff --git a/hello.c b/hello.c
new file mode 100644
index 0000000..03bde36
--- /dev/null
+++ b/hello.c
@@ -0,0 +1,5 @@
+#include <stdio.h>
+int main() {
+   printf("Hello, World!\n");
+   return 0;
+}
....

== Basic concepts

=== Repository

A _repository_ (_repo_ for short) is a database that represents the
history of the project as a set of commits (see <<Commits>> below). It
is stored in the `.git` sub-directory, along with other things, like
the index (see below).

=== Git tracks content

Every object stored by Git (files, commits, trees, etc.) is identified
by its SHA1 (or sometimes just SHA) hash. This is a cryptographic
160-bit (shown as 40 hex characters) digest of the object. It
represents the content of the file. There are about 10^48^
possibilities. The value is essentially unique for every unique object
in your repository. In fact, it is essentially unique for every unique
object in every repository. So if two objects, say files, in two different
repositories have the same SHA1 they can be expected to have the same
content.

=== Commits

A _commit_ consists of:

    * the hash of the _tree_ that represents the files (and directory structure)
    * author information: name, e-mail, time
    * committer information: name, e-mail, time
    * commit message
    * the hash(es) of parent commit(s)

that corresponds to the state of the project at that  point. It also
is represented by its  SHA1 hash, which as said before, is essentially
unique.  So if two commits in two repositories have the same SHA1,
    they can be expected to have the same content (including history)
    to that point.

NOTE: The commit where you are working is referred to as the `HEAD` commit
and is usually the tip of a branch (see <<Branches>> below).  If it is
not the tip of a branch, it is a _detached_ `HEAD`.

=== Branches

A _branch_ is a sequence of commits that provides a history of the
changes in the project. Generally speaking all commits are on
branches. The most recent commit on a branch is referred to as the
_tip_. The main branch is usually called `master`; it usually has the
main line of development. There can be other branches for various
uses, including:

* _feature_ branches to develop new features
* _maintenance_ branches for an existing release.

NOTE: When you _checkout_ a branch, you are automatically put at the
tip. A branch points to its tip commit.

NOTE: Branching is intended to be easy and fast. It can be used for
even the smallest changes. That is a good idea. You never know when a
change is going to get bigger than you expected.

=== Tags

A _tag_ is used to mark a specific commit for future reference. It is
basically just a pointer to the commit. This could be to identify a
commit that was used for a release or just to keep track of it. There
are annotated tags and lightweight tags.

=== How content is organized

At any given time, in addition to the repository, we are working with
three distinct representations of the files in the project:

. The current `HEAD` commit, which is a saved state of the project.

. The _index_ (or cache) which is where changes are staged for the
next commit. When you make a commit, you are storing what is in
the index. If there are no changes in the index, there is nothing to
commit.

. The _working directory_, which is what you edit and what you see
with `ls`.

=== Workflow

. Checkout a specific commit (by branch, tag, or hash). This becomes
the `HEAD` commit. If you don't checkout a specific commit, you are
just working at whatever the current `HEAD` is.

. Modify the working directory, which starts out with the same files
as the `HEAD` commit.

. `add` the changes to the index, which also started out with the same
files as the `HEAD` commit. When a file is added to index, it is
considered _staged_. 

. `commit` the files in the index to make a new commit. The new commit
becomes the new `HEAD`.

IMPORTANT: After ``add``ing changes to the index, you can make further
changes to the affected files, but you will need to `add` the
additional changes.  Each `add` adds the content you have
changed; it is not a "marker" that the working directory has changed.

NOTE: You don't have to add all your changes to the index before committing.
A commit will only use the changes in the index. This allows you
flexibility to commit subsets of changes.

== Making a change

Let's greet more than one world.

=== Update the working directory

....
$ cp /tmp/hellos.c hello.c
$ cat hello.c
#include <stdio.h>
int main() {
   printf("Hello, Worlds!\n");
   return 0;
}
....

=== Our status: modified, not staged
....
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   hello.c

no changes added to commit (use "git add" and/or "git commit -a")
....

NOTE: More undo hints!

=== How is this different than what is in the index

Use the `diff` feature.
....
$ git diff
diff --git a/hello.c b/hello.c
index 03bde36..1e2cfea 100644
--- a/hello.c
+++ b/hello.c
@@ -1,5 +1,5 @@
 #include <stdio.h>
 int main() {
-   printf("Hello, World!\n");
+   printf("Hello, Worlds!\n");
    return 0;
 }
....

[NOTE]
====

There are a lot of very useful features in `diff`. Here are just a
few:

 * `git diff`  -- difference index _to_ working directory
 * `git diff HEAD` -- difference `HEAD` _to_ working directory
 * `git diff --cached` -- difference `HEAD` _to_ cache (index)

You can also add file or directory names at the end of the command to
restrict it to specific files or directories.

====

//$ make

//cc    -c -o hello.o hello.c
//cc   hello.o   -o hello
//$ ./hello
//Hello, Worlds!

=== Add it to index
....
$ git add .

$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   hello.c

....

NOTE: Adding files that have not changed has no effect on the index.
In this case, adding `.` picks up only the modified file.

[NOTE]
====

Other useful index (and working directory) manipulation commands:

* `git rm <files>` -- to remove files
* `git mv ... ...` - to rename files

Using these commands makes the changes easier than manipulating the
files in the working directory directly.

====

=== Commit it
....
$ git commit -m "Change to worlds"
[master 958ad36] Change to worlds
 1 file changed, 1 insertion(+), 1 deletion(-)

....
=== The log
....
$ git log
commit 958ad362fe6a1661e07e0765b13b74ae7475fd57 (HEAD -> master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:35:39 2020 -0400

    Change to worlds

commit bdca79e9499918240c27ff43c6598b26db6c0893
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit
....

//$ git checkout bdca79e94
//Note: switching to 'bdca79e94'.
//
//You are in 'detached HEAD' state. You can look around, make experimental
//changes and commit them, and you can discard any commits you make in this
//state without impacting any branches by switching back to a branch.
//
//If you want to create a new branch to retain commits you create, you may
//do so (now or later) by using -c with the switch command. Example:
//
//  git switch -c <new-branch-name>
//
//Or undo this operation with:
//
//  git switch -
//
//Turn off this advice by setting config variable advice.detachedHead to false
//
//HEAD is now at bdca79e Initial commit
//$ git log
//commit bdca79e9499918240c27ff43c6598b26db6c0893 (HEAD)
//Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
//Date:   Sat Jun 6 15:31:42 2020 -0400
//
//    Initial commit
//$ make
//cc    -c -o hello.o hello.c
//cc   hello.o   -o hello
//$ ./hellp
//-bash: ./hellp: No such file or directory
//$ ./hello
//Hello, World!
//$ git checkout master
//Previous HEAD position was bdca79e Initial commit
//Switched to branch 'master'
//$ git log
//commit 958ad362fe6a1661e07e0765b13b74ae7475fd57 (HEAD -> master)
//Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
//Date:   Sat Jun 6 15:35:39 2020 -0400
//
//    Change to worlds
//
//commit bdca79e9499918240c27ff43c6598b26db6c0893
//Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
//Date:   Sat Jun 6 15:31:42 2020 -0400
//
//    Initial commit
//$ make
//cc    -c -o hello.o hello.c
//cc   hello.o   -o hello
//$ ./hello 
//Hello, Worlds!
== Add a new feature on a new branch

In this case we are going to expand our greeting to galaxies.

=== Create new branch

Using `checkout -b` will create create a new branch at the current
`HEAD` commit and leave it checked out.

....
$ git checkout -b galaxy
Switched to a new branch 'galaxy'
....

NOTE: The same approach can be used to create a maintenance branch.

=== Log

....
$ git log
commit 958ad362fe6a1661e07e0765b13b74ae7475fd57 (HEAD -> galaxy, master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:35:39 2020 -0400

    Change to worlds

commit bdca79e9499918240c27ff43c6598b26db6c0893
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit
....

NOTE: `HEAD` is the tip of `galaxy` and also happens to be the same
commit as the tip of `master`.

=== Show branches
....
$ git branch -a
* galaxy
  master
....

The `*` marks the active branch.

=== Make the change in the new branch

. Update working directory
+
....
$ cp /tmp/hellog.c hello.c
$ cat hello.c
#include <stdio.h>
int main() {
   printf("Hello, Galaxy!\n");
   return 0;
}
....

. Check status
+
....
$ git status
On branch galaxy
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   hello.c

no changes added to commit (use "git add" and/or "git commit -a")
....

. Add it to the index
+
You can add files selectively depending on what you want to commit.
+
....
$ git add hello.c

$ git status
On branch galaxy
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   hello.c
....

. Commit it
+
....
$ git commit -m "Switch to galaxy"
[galaxy 71b0756] Switch to galaxy
 1 file changed, 1 insertion(+), 1 deletion(-)
....

. View current log
+
....
$ git log
commit 71b0756022a3c2d1d2008a582d9ccc2ebec40688 (HEAD -> galaxy)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:40:45 2020 -0400

    Switch to galaxy

commit 958ad362fe6a1661e07e0765b13b74ae7475fd57 (master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:35:39 2020 -0400

    Change to worlds

commit bdca79e9499918240c27ff43c6598b26db6c0893
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit
....

NOTE: The latest cmmmit is the `HEAD` commit, which is the tip of the
`galazy` branch. The preceding commit is still the tip of `master*. We
see it because it is in the history of this branch.

== Merge the changes into the `master` branch

This will bring the changes in the feature branch into the *master`
branch

=== Switch back to the `master` branch

....
$ git checkout master
Switched to branch 'master'

$ git status
On branch master
nothing to commit, working tree clean

$ git log
commit 958ad362fe6a1661e07e0765b13b74ae7475fd57 (HEAD -> master)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:35:39 2020 -0400

    Change to worlds

commit bdca79e9499918240c27ff43c6598b26db6c0893
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit
....

=== Merge the changes from the feature branch

....
$ git merge galaxy
Updating 958ad36..71b0756
Fast-forward
 hello.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
....
 
[NOTE]
====

The merge was `Fast-forward`. This makes the changes from the `galaxy`
branch look like they were originally added to the `master` branch
(see log output below). This is good for small changes, but sometimes
you want to have a separate _merge commit_ to record the path of a
significant development. For that case, you can  use the `--no-ff`
option.

You won't be able to Fast-forward if the branch you are merging onto
    was changed since it was branched off from. However, you can
    `rebase` the other branch to the target branch to get a similar
    effect.

====
=== Look at the log now
 
The new commit has the same SHA as the `HEAD` commit on `galaxy`
 
....
$ git log
commit 71b0756022a3c2d1d2008a582d9ccc2ebec40688 (HEAD -> master, galaxy)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:40:45 2020 -0400

    Switch to galaxy

commit 958ad362fe6a1661e07e0765b13b74ae7475fd57
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:35:39 2020 -0400

    Change to worlds

commit bdca79e9499918240c27ff43c6598b26db6c0893
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit
....
 
NOTE: Now `HEAD` is the tip of `master` and
also happens to be the same commit as the tip of `galaxy`.

=== Delete the feature branch
....
$ git branch -d galaxy
Deleted branch galaxy (was 71b0756).
....

//$ make
//cc    -c -o hello.o hello.c
//cc   hello.o   -o hello
//$ ./hello 
//Hello, Galaxy!
//$ 

== Add a tag to a commit

To add a lightweight tag:

....
$ git tag v1

$ git log
commit 71b0756022a3c2d1d2008a582d9ccc2ebec40688 (HEAD -> master, tag: v1)
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:40:45 2020 -0400

    Switch to galaxy

commit 958ad362fe6a1661e07e0765b13b74ae7475fd57
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:35:39 2020 -0400

    Change to worlds

commit bdca79e9499918240c27ff43c6598b26db6c0893
Author: Ed Himwich <51408905+wehimwich@users.noreply.github.com>
Date:   Sat Jun 6 15:31:42 2020 -0400

    Initial commit
....

The tag is listed for the commit.

NOTE: The `galaxy` branch is no longer shown, since it has been
deleted. Its former commits are still there since they were merged
onto `master`.

[NOTE]
====

The tag can be used to checkout that commit even after the branch has
moved past it. For example to create a maintenance branch for old
commit tagged as `v1`, you can use:

....
$ git checkout v1
$ git checkout -b m1
....

Life is easier if branch and tags don't conflict.
====

[NOTE]
====
List all tags:
....
$ git tag
v1
....
====

== Resources

This is a small selection of the available resources.

=== _man_ pages
You can get help on any command from the _man_ page by using the
`--help` option, like:

....
$ git commit --help
....

=== On the web

There is a lot of useful information, at all levels, that is only a
search away on the web. Most of it seems to be trustworthy, but it is
obviously better if you understand enough to evaluate it before using
it.

Some useful links:

* https://www.atlassian.com/git/tutorials  -- Tutorials
* https://git-scm.com/  -- Git community online
* https://chris.beams.io/posts/git-commit/  -- How to write a Git commit message
* https://ohshitgit.com/  -- Some recovery strategies
* https://stackoverflow.com/questions/16562121/git-diff-head-vs-staged

=== Books

* "Version Control with Git, 2nd Edition"
by Jon Loeliger, Matthew McCullough,
Released August 2012,
Publisher(s): O'Reilly Media, Inc.,
ISBN: 9781449316389

== Git commands mentioned


.Summary of Git commands mentioned
[cols="1,2"]
|=============================================================
| Command | Description


| `git init`|  Initialize repository
| `git status` | Check status
| `git add .` | Add current directory structure to index
| `git add <files>` | Add `<files>` to index
| `git commit -m "Initial commit"` | Commit with commit message
| `git commit` | Commit without commit message (an editor is run)
| `git log` | Show history from current `HEAD`
| `git log --stat` | History with change statistics
| `git log -p` | History with patch listing
| `git rm <files>` | Remove `<files>`
| `git mv ... ...` | Rename files
| `git diff` | difference index _to_ working directory
| `git diff HEAD` | difference `HEAD` _to_ working directory
| `git diff --cached` | difference `HEAD` _to_ cache (index)
| `git checkout -b galaxy` | Starting at `HEAD` create a new branch (`galaxy`) and check it out
| `git branch -a` | List all branches
| `git checkout master` | Checkout branch (`master`)
| `git merge galaxy` | Merge branch (`galaxy`) into current branch
| `git branch -d galaxy` | Delete branch (`galaxy`)
| `git tag v1` | Add tag (`v1`) to current `HEAD`
| `git checkout v1` | Checkout tag (`v1`)
| `git tag` | List tags
| `git commit --help` |Show help
|=============================================================
